// This file is generated by Firebase Genkit.
// prettier-ignore
'use server';
/**
 * @fileOverview A flow that explains the Exnus Protocol in a simplified manner.
 *
 * - explainExnusProtocol - A function that triggers the Exnus Protocol explanation flow.
 * - ExplainExnusProtocolInput - The input type for the explainExnusProtocol function.
 * - ExplainExnusProtocolOutput - The return type for the explainExnusProtocol function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ExplainExnusProtocolInputSchema = z.object({
  query: z.string().describe('The specific aspect of the Exnus Protocol to explain, or a general request for an overview.'),
});
export type ExplainExnusProtocolInput = z.infer<typeof ExplainExnusProtocolInputSchema>;

const ExplainExnusProtocolOutputSchema = z.object({
  explanation: z.string().describe('A simplified explanation of the Exnus Protocol.'),
});
export type ExplainExnusProtocolOutput = z.infer<typeof ExplainExnusProtocolOutputSchema>;

export async function explainExnusProtocol(input: ExplainExnusProtocolInput): Promise<ExplainExnusProtocolOutput> {
  return explainExnusProtocolFlow(input);
}

const explainExnusProtocolPrompt = ai.definePrompt({
  name: 'explainExnusProtocolPrompt',
  input: {schema: ExplainExnusProtocolInputSchema},
  output: {schema: ExplainExnusProtocolOutputSchema},
  prompt: `You are an AI assistant specialized in explaining complex web3 protocols in a simple and easy-to-understand manner.

  The user is asking for an explanation of the Exnus Protocol. Please provide a clear and concise explanation based on the user's query.

  Query: {{{query}}}
  `,
});

const explainExnusProtocolFlow = ai.defineFlow(
  {
    name: 'explainExnusProtocolFlow',
    inputSchema: ExplainExnusProtocolInputSchema,
    outputSchema: ExplainExnusProtocolOutputSchema,
  },
  async input => {
    const {output} = await explainExnusProtocolPrompt(input);
    return output!;
  }
);
